name: "Code coverage-reporter"
description: "Comments a pull request with code coverage report"
author: "Tonye Jack"
branding:
  icon: "check"
  color: "white"
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  coverage-command:
    description: "Specify a coverage command to run the test."
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
